### ISSUE TITLE
how do you apply the different styles you created to the prompt?

### ISSUE THREAD

**Issue by rv1985** [willwulfken/MidJourney-Styles-and-Keywords-Reference#23]
Hi, If I want to add a specific style of yours to my prompt, where would that fit?

thanks

### Discussed in https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **willwulfken** August 10, 2022</sup>
Submit general and miscellaneous questions here</div>

**Comment by willwulfken** [comment]
I'm not sure what you mean specifically. If you mean where would it fit in your prompt, you can place the style/keywords anywhere. Putting them in different places may produce different results however.
