### ISSUE TITLE
possible copyright?

### ISSUE THREAD

**Issue by altdann** [willwulfken/MidJourney-Styles-and-Keywords-Reference#24]
I Have tried to make an image earlier with Hendrick's Gin, Pickle Rick and "dancing with Elvis Presley" but it was far from it. is there a rule against it? It did give me HR Giger though.
I even tried Weight on the "with"
" https://s.mj.run/_wpabfsxtEg in a suite smoking cigars with:: 3 Elvis Presley:: 2, photography, cinematic 4 --s 100 --q 2 "
_https://cdn.discordapp.com/attachments/997271802420142110/1066247772921147454/IllEatYourCat_in_a_suite_smoking_cigars_with_e1568321-e816-428d-ae30-a980c665141f.png_
With Hendrick's Gin, Ai steered clear even from the name x))
_https://cdn.discordapp.com/attachments/989268410171006976/1066081683012603954/IllEatYourCat_Hendricks_Gin_in_its_own_brand_animation_style_a__e448952a-fd9a-4287-b74d-4659dcb17604.png_

**Comment by willwulfken** [comment]
Most likely, the AI either wasn't trained with those specific images or did not learn them well
