### ISSUE TITLE
General

### ISSUE THREAD

**Issue by peapodgrrl** [willwulfken/MidJourney-Styles-and-Keywords-Reference#25]
### Discussed in https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **willwulfken** August 10, 2022</sup>
General Discussion</div>

Can someone help a discord idiot? I need to find the original prompt (seed, etc). I am doing well with MJ not so much Discord. I clicked the envelope. I  click where it says DM and I can't get to it. I need that prompt pretty badly. Can someone help a discord moron?

Thank you.

**Comment by willwulfken** [comment]
Make sure you have already DMed MidJourney before

It will be right at the top
![image](https://user-images.githubusercontent.com/6042799/213945489-4be12f2b-cf62-4a62-ae3c-b6e2dd6404ec.png)

**Comment by willwulfken** [comment]
I would send a message in the MidJourney server in the channel #member-support (if you are a paid user)
If you are not a paid member, use #trial-support
