### ISSUE TITLE
zip file is invalid

### ISSUE THREAD

**Issue by seankklol** [willwulfken/MidJourney-Styles-and-Keywords-Reference#37]
![image](https://user-images.githubusercontent.com/122267481/222938643-70b7c61f-fa54-44cf-ac30-33a2606776e4.png)

**Comment by willwulfken** [comment]
This is because the whole zip file was not downloaded. The total repo size is around 17GB if that helps.

**Comment by willwulfken** [comment]
This has been fixed as of recent commits. The total size of the repo is now ~2.5 GB as opposed to 18.4 GB.
Even better, the image size and quality should have no noticeable difference from before.
