### ISSUE TITLE
how to download the project? 

### ISSUE THREAD

**Issue by angelOnly** [willwulfken/MidJourney-Styles-and-Keywords-Reference#39]
the project is too large, git clone command can not download the project, https also can not

**Comment by willwulfken** [comment]
The project is massive. I've been thinking of ways to make downloading easier but haven't implemented them yet.

This needs to be updated: [Midjourney Styles and Keywords Reference Light](https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference-Light)
However it's only 1.2 GB as opposed to 18.4 GB

**Comment by willwulfken** [comment]
This has been fixed as of the most recent commits. The total size of the repo is now ~2.5 GB as opposed to 18.4 GB.
Even better, the image size and quality should have no noticeable difference from before.

**Comment by Entrepincome** [comment]
After downloading this repository, i got nothing in files. Why is that??
Tell me a way to download it ASAP.

**Comment by willwulfken** [comment]
> After downloading this repository, i got nothing in files. Why is that?? Tell me a way to download it ASAP.

When you download it, if not all the data was downloaded correctly, you will have an invalid zip file.

If you don't know how to download it at all you can do the following:

On the main page, there should be a "download" button the the top right. In the drop down select "download zip". This will download a few gigabytes of files.

If you just need a list of the words you can go to "releases" and download that. Those files range from kilobytes to megabytes, so relatively very small.
